uploads = []
outputs = []

[[generated]]
id = "YoTIMoOEi1wEUVFNjAxiu"
uri = "file://artifacts/sairag-website/src/assets/hero-bg.png"
type = "image"
title = "hero-facade-bg"

[[generated]]
id = "uRpnXgj-SGMV6erKtKnJG"
uri = "file://artifacts/sairag-website/src/assets/services-bg.png"
type = "image"
title = "services-facade-detail"

[[generated]]
id = "v8EPzlGbYz7hiWc_KMVVp"
uri = "file://artifacts/sairag-website/src/assets/about-bg.png"
type = "image"
title = "about-glass-architecture"
